export default {
    name: 'projectInfo',
    title: 'Project Info',
    type: 'document',
    fields: [
      {name:"projectResponsiveImages",
        title: "Project Image Various Sizes",
        description: "Project Image Sizes for desktop mobile tablet",
        type: "array",
        of: [{ type: "image",
                options: {
                    hotspot: true,
                }, 
            }],
      },
      {
        name:"projectTitle",
        title: "Project Title",
        description: "Project Title",
        type: "string",
      },
       {name:"projectDescription",
        title: "Project Description",
        description: "Project description",
        type: "string",
      },
       {name:"projectHistory",
        title: "Project History",
        type: "string",
      },
       {name:"website",
        title: "Website",
        description: "Project Website",
        type: "string",
      },
       {name:"projectStack",
        title: "Project Stack",
        description: "Stack used in this project",
        type: "string",
      },
       {name:"source",
        title: "Project Source Code",
        type: "string",
      },
       {name:"disclaimer",
        title: "Disclaimer",
        description: "Extra info for the clients",
        type: "string",
      },
       {name:"projectGallery",
        title: "Project Gallery",
        description: "Compendium of four Project Images",
        type: "array",
        of: [{ type: "image",
                options: {
                    hotspot: true,
                }, 
            }],
      },
       {name:"projectSticker",
        title: "Project Sticker Image",
        description: "Project Sticker Image",
        type: "image",
        options: {
          hotspot: true,
        },
      },
    ],
  
    
  }
  